/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imager.Gui;

/**
 *
 * @author zk
 */
public class Gui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gui.class.getName());

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        setupMenu();
    }

    private java.awt.image.BufferedImage currentImage = null;
    private String currentPath = null;

    private void setupMenu() {
        javax.swing.JMenuBar menubar = new javax.swing.JMenuBar();

        javax.swing.JMenu fileMenu = new javax.swing.JMenu("File");
        javax.swing.JMenuItem openItem = new javax.swing.JMenuItem("Open...");
        openItem.addActionListener(e -> {
            javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
            int rv = fc.showOpenDialog(this);
            if (rv == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File f = fc.getSelectedFile();
                try {
                    currentImage = imager.Editor.Dithering.loadImage(f.getAbsolutePath());
                    currentPath = f.getAbsolutePath();
                    javax.swing.JOptionPane.showMessageDialog(this, "Loaded: " + f.getName());
                } catch (java.io.IOException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to load: " + ex.getMessage());
                }
            }
        });
        fileMenu.add(openItem);
        javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem("Exit");
        exitItem.addActionListener(e -> System.exit(0));
        fileMenu.add(exitItem);

        javax.swing.JMenu resizeMenu = new javax.swing.JMenu("Resize");
        javax.swing.JMenuItem r1 = new javax.swing.JMenuItem("1/5 (20%)");
        r1.addActionListener(e -> doResize(0.2, "1-5"));
        javax.swing.JMenuItem r2 = new javax.swing.JMenuItem("1/2 (50%)");
        r2.addActionListener(e -> doResize(0.5, "1-2"));
        javax.swing.JMenuItem r3 = new javax.swing.JMenuItem("2/3 (66%)");
        r3.addActionListener(e -> doResize(2.0/3.0, "2-3"));
        javax.swing.JMenuItem rOrig = new javax.swing.JMenuItem("Original (100%)");
        rOrig.addActionListener(e -> doResize(1.0, "orig"));
        resizeMenu.add(r1);
        resizeMenu.add(r2);
        resizeMenu.add(r3);
        resizeMenu.add(rOrig);

        menubar.add(fileMenu);
        menubar.add(resizeMenu);
        this.setJMenuBar(menubar);
    }

    private void doResize(double scale, String tag) {
        if (currentImage == null || currentPath == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No image loaded. Use File -> Open first.");
            return;
        }
        try {
            java.awt.image.BufferedImage out = imager.Editor.Dithering.resize(currentImage, scale);
            imager.Editor.Dithering.saveImage(out, currentPath, "resized_" + tag);
            javax.swing.JOptionPane.showMessageDialog(this, "Resized and saved (scale=" + scale + ")");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Resize failed: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
